class AppString{
  static const String appName="POS";
  static const String sale="Sale";
  static const String receipt="Receipt";
  static const String item="Item";
  static const String setting="Setting";
  static const String items="Items";
  static const String categories="Categories";
  static const String search="Search";
  static const String createItem="Create Item";
  static const String save="SAVE";
  static const String code="Code";
  static const String name="Name";
  static const String salePrice="Sale Price";
  static const String purchasePrice="Purchase Price";
  static const String cost="Cost";
  static const String choosePhoto="CHOOSE PHOTO";
  static const String takePhoto="TAKE PHOTO";
  static const String createCategory="Create Category";
  static const String updateCategory="Update Category";
  static const String enterCode="Enter Code";
  static const String enterName="Enter Name";
  static const String savedCategory="Saved Category";
  static const String deleted="Deleted";
  static const String somethingWentWrong="Something Went Wrong";
  static const String duplicateCode="Existing Code! Try another Code";
  static const String notFoundCategory="Not found category";
  static const String savedItem="Saved Item";
}